# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
# SPDX-FileCopyrightText: 2025 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Apache NiFi paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ nifi_uid }}"
    group: "{{ nifi_gid }}"
  with_items:
    - "{{ nifi_base_path }}"
    - "{{ nifi_data_path }}"
    - "{{ nifi_scripts_path }}"
    - "{{ nifi_certs_path }}"
    - "{{ nifi_data_path }}/database_repository"
    - "{{ nifi_data_path }}/flowfile_repository"
    - "{{ nifi_data_path }}/content_repository"
    - "{{ nifi_data_path }}/provenance_repository"
    - "{{ nifi_data_path }}/state"
    - "{{ nifi_data_path }}/logs"
    - "{{ nifi_data_path }}/conf"

- name: Ensure Apache Nifi temporary configuration customization directory exists
  ansible.builtin.tempfile:
    state: directory
    suffix: nifi
  changed_when: false
  register: nifi_tempdir

- name: Copy Apache NiFi default configuration files for customization
  ansible.builtin.copy:
    src: "{{ role_path }}/files/conf/{{ item }}"
    dest: "{{ nifi_tempdir.path }}/{{ item }}"
    mode: "0640"
    owner: "{{ nifi_uid }}"
    group: "{{ nifi_gid }}"
  changed_when: false
  with_items:
    - authorizers.xml
    - bootstrap.conf
    - logback.xml
    - login-identity-providers.xml
    - nifi.properties
    - state-management.xml
    - zookeeper.properties

- name: Ensure Apache NiFi XML configuration files have the defined adjustments
  community.general.xml:
    path: "{{ nifi_tempdir.path }}/{{ item.0.file }}"
    xpath: "{{ item.1.xpath }}"
    value: "{{ item.1.value | default(omit) }}"
    state: "{{ item.1.state | default('present') }}"
    pretty_print: "{{ item.1.pretty_print | default(true) }}"
  changed_when: false
  with_subelements:
    - - { "file": "authorizers.xml", "parameters": "{{ nifi_conf_authorizers_xml }}" }
      - { "file": "logback.xml", "parameters": "{{ nifi_conf_logback_xml }}" }
      - { "file": "login-identity-providers.xml", "parameters": "{{ nifi_conf_login_identity_providers_xml }}" }
      - { "file": "state-management.xml", "parameters": "{{ nifi_conf_state_management_xml }}" }
    - parameters

- name: Ensure Apache NiFi properties configuration files have the defined adjustments
  ansible.builtin.lineinfile:
    path: "{{ nifi_tempdir.path }}/{{ item.0.file }}"
    line: "{{ item.1.key }}={{ item.1.value }}"
    regexp: "^{{ item.1.key }}="
    state: "{{ item.1.state | default('present') }}"
  changed_when: false
  with_subelements:
    - - { "file": "nifi.properties", "parameters": "{{ nifi_conf_nifi_properties }}" }
      - { "file": "zookeeper.properties", "parameters": "{{ nifi_conf_zookeeper_properties }}" }
      - { "file": "bootstrap.conf", "parameters": "{{ nifi_conf_bootstrap_conf }}" }
    - parameters

- name: Ensure Apache NiFi adjusted configuration files installed
  ansible.builtin.copy:
    src: "{{ nifi_tempdir.path }}/{{ item.file }}"
    dest: "{{ nifi_data_path }}/conf/{{ item.file }}"
    remote_src: true
    mode: "0640"
    owner: "{{ nifi_uid }}"
    group: "{{ nifi_gid }}"
  with_items:
    - { "file": "authorizers.xml" }
    - { "file": "logback.xml" }
    - { "file": "login-identity-providers.xml" }
    - { "file": "state-management.xml" }
    - { "file": "nifi.properties" }
    - { "file": "zookeeper.properties" }
    - { "file": "bootstrap.conf" }

- name: Ensure Apache NiFi support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ nifi_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ nifi_uid }}"
    group: "{{ nifi_gid }}"
  with_items:
    - env
    - labels

- name: Ensure Apache NiFi custom scripts installed
  ansible.builtin.copy:
    src: "{{ role_path }}/files/scripts/{{ item }}"
    dest: "{{ nifi_scripts_path }}/{{ item }}"
    mode: "0751"
    owner: "{{ nifi_uid }}"
    group: "{{ nifi_gid }}"
  with_items:
    - common.sh
    - start.sh

- name: Generate private key
  community.crypto.openssl_privatekey:
    path: "{{ nifi_certs_path }}/private.key"
    owner: "{{ nifi_uid }}"
    group: "{{ nifi_gid }}"
    mode: "0600"

- name: Generate CSR
  community.crypto.openssl_csr:
    path: "{{ nifi_certs_path }}/certificate.csr"
    privatekey_path: "{{ nifi_certs_path }}/private.key"
    common_name: "{{ nifi_hostname }}"
    organization_name: "organization_name"
    country_name: "CZ" # Christmas island
    owner: "{{ nifi_uid }}"
    group: "{{ nifi_gid }}"
    mode: "0644"

- name: Generate self-signed CA certificate
  community.crypto.x509_certificate:
    path: "{{ nifi_certs_path }}/ca-cert.pem"
    privatekey_path: "{{ nifi_certs_path }}/private.key"
    csr_path: "{{ nifi_certs_path }}/certificate.csr"
    provider: selfsigned
    owner: "{{ nifi_uid }}"
    group: "{{ nifi_gid }}"
    mode: "0644"

- name: Generate server certificate signed by CA
  community.crypto.x509_certificate:
    path: "{{ nifi_certs_path }}/nifi-cert.pem"
    privatekey_path: "{{ nifi_certs_path }}/private.key"
    csr_path: "{{ nifi_certs_path }}/certificate.csr"
    provider: ownca
    ownca_path: "{{ nifi_certs_path }}/ca-cert.pem"
    ownca_privatekey_path: "{{ nifi_certs_path }}/private.key"
    mode: "0644"

- name: Create JKS keystore with certificate and private key
  community.general.java_keystore:
    name: nifi-key
    certificate_path: "{{ nifi_certs_path }}/nifi-cert.pem"
    private_key_path: "{{ nifi_certs_path }}/private.key"
    password: "{{ nifi_self_signed_cert_passphrase }}"
    dest: "{{ nifi_certs_path }}/keystore.jks"
    keystore_type: jks
    owner: "{{ nifi_uid }}"
    group: "{{ nifi_gid }}"
    mode: "0600"

- name: Import CA certificate into JKS truststore
  community.general.java_cert:
    cert_path: "{{ nifi_certs_path }}/ca-cert.pem"
    cert_alias: nifi-ca
    keystore_path: "{{ nifi_certs_path }}/truststore.jks"
    keystore_pass: "{{ nifi_self_signed_cert_passphrase }}"
    keystore_type: JKS
    keystore_create: true
    trust_cacert: true
    state: present
    owner: "{{ nifi_uid }}"
    group: "{{ nifi_gid }}"
    mode: "0600"

- name: Run if self-building of Apache NiFi container image is not enabled
  when: "not nifi_container_image_self_build | bool"
  block:
    - name: Ensure Apache NiFi container image is pulled via community.docker.docker_image
      when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
      community.docker.docker_image:
        name: "{{ nifi_container_image }}"
        source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
        force_source: "{{ nifi_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
        force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else nifi_container_image_force_pull }}"
      register: result
      retries: "{{ devture_playbook_help_container_retries_count }}"
      delay: "{{ devture_playbook_help_container_retries_delay }}"
      until: result is not failed

    - name: Ensure Apache NiFi container image is pulled via ansible.builtin.command
      when: devture_systemd_docker_base_container_image_pull_method == 'command'
      ansible.builtin.command:
        cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ nifi_container_image }}"
      register: result
      retries: "{{ devture_playbook_help_container_retries_count }}"
      delay: "{{ devture_playbook_help_container_retries_delay }}"
      until: result is not failed
      changed_when: "'Downloaded newer image' in result.stdout"

- name: Run if self-building of Apache NiFi container image is enabled
  when: "nifi_container_image_self_build | bool"
  block:
    - name: Ensure Apache NiFi repository is present on self-build
      ansible.builtin.git:
        repo: "{{ nifi_container_image_self_build_repo }}"
        version: "{{ nifi_container_image_self_build_repo_version }}"
        dest: "{{ nifi_container_image_self_build_src_files_path }}"
        force: "yes"
      register: nifi_git_pull_results

    - name: Ensure Apache NiFi container image is built
      community.docker.docker_image:
        name: "{{ nifi_container_image_self_build_name }}"
        source: build
        force_source: "{{ nifi_git_pull_results.changed if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
        force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else nifi_git_pull_results.changed }}"
        build:
          dockerfile: Dockerfile
          path: "{{ nifi_container_image_self_build_src_files_path }}"
          pull: true
          args:

- name: Ensure Apache NiFi container network is created via community.docker.docker_network
  when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ nifi_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure Apache NiFi container network is created via ansible.builtin.command
  when: devture_systemd_docker_base_container_network_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} network create
      {% if devture_systemd_docker_base_ipv6_enabled %}--ipv6{% endif %}
      {{ devture_systemd_docker_base_container_networks_driver_options_string }}
      {{ nifi_container_network }}
  register: network_creation_result
  changed_when: network_creation_result.rc == 0
  failed_when: network_creation_result.rc != 0 and 'already exists' not in network_creation_result.stderr

- name: Ensure Apache NiFi systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/nifi.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ nifi_identifier }}.service"
    mode: "0644"
