# SPDX-FileCopyrightText: 2023 Julian-Samuel GebÃ¼hr
# SPDX-FileCopyrightText: 2023 MASH project contributors
# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
# SPDX-FileCopyrightText: 2025 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if required Apache NiFi settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - nifi_uid
    - nifi_gid
    - nifi_hostname
    - nifi_path_prefix
    - nifi_container_network
    - nifi_self_signed_cert_passphrase
    - nifi_sensitive_props_key
    - nifi_login_password

- name: Run if Traefik is enabled
  when: nifi_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Apache NiFi are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - nifi_container_labels_traefik_hostname
        - nifi_container_labels_traefik_path_prefix

    - name: Fail if nifi_container_labels_traefik_path_prefix is different than /
      ansible.builtin.fail:
        msg: >-
          nifi_container_labels_traefik_path_prefix (`{{ nifi_container_labels_traefik_path_prefix }}`) must be `/`.
          Apache NiFi does not support hosting under a subpath yet.
      when: "nifi_container_labels_traefik_path_prefix != '/'"

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `nifi_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if nifi_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          nifi_container_labels_traefik_path_prefix (`{{ nifi_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/nifi`).
      when: "nifi_container_labels_traefik_path_prefix != '/' and nifi_container_labels_traefik_path_prefix[-1] == '/'"
