# SPDX-FileCopyrightText: 2023 Julian-Samuel GebÃ¼hr
# SPDX-FileCopyrightText: 2023 MASH project contributors
# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if required Apache Answer settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - answer_uid
    - answer_gid
    - answer_hostname
    - answer_path_prefix
    - answer_container_network

- name: Run if automatic installation with environment variables is enabled
  when: answer_environment_variables_auto_install | bool
  block:
    - name: Fail if required Apache Answer settings for automatic installation not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - answer_database_type
        - answer_environment_variables_admin_email
        - answer_environment_variables_admin_password

    - name: Fail if Apache Answer password is more than 32 characters in length
      ansible.builtin.fail:
        msg: >-
          Password specified to `answer_environment_variables_admin_password` must be at maximum 32 characters in length
      when: "answer_environment_variables_admin_password | length > 32"

    - name: Fail if Apache Answer database type is invalid
      ansible.builtin.fail:
        msg: >-
          answer_database_type must be 'mysql', 'postgres', or 'sqlite'.
      when: "answer_database_type not in ['mysql', 'postgres', 'sqlite']"

    - name: Fail if required Apache Answer + MySQL integration settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`) when `answer_database_type` is `mysql`
      when: "answer_database_type == 'mysql' and lookup('vars', item, default='') | string | length == 0"
      with_items:
        - answer_database_mysql_hostname
        - answer_database_mysql_password

    - name: Fail if required Apache Answer + Postgres integration settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`) when `answer_database_type` is `postgres`
      when: "answer_database_type == 'postgres' and lookup('vars', item, default='') | string | length == 0"
      with_items:
        - answer_database_postgres_hostname
        - answer_database_postgres_password

- name: Run if Traefik is enabled
  when: answer_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Apache Answer are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - answer_container_labels_traefik_hostname
        - answer_container_labels_traefik_path_prefix

    - name: Fail if answer_container_labels_traefik_path_prefix is different than /
      ansible.builtin.fail:
        msg: >-
          answer_container_labels_traefik_path_prefix (`{{ answer_container_labels_traefik_path_prefix }}`) must be `/`.
          Apache Answer does not support hosting under a subpath yet.
      when: "answer_container_labels_traefik_path_prefix != '/'"

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `answer_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if answer_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          answer_container_labels_traefik_path_prefix (`{{ answer_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/answer`).
      when: "answer_container_labels_traefik_path_prefix != '/' and answer_container_labels_traefik_path_prefix[-1] == '/'"
